name: build-and-upload
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run: pnpm i && pnpm run build
      - name: Upload bundle to Webflow CDN bucket
        run: npx wrangler r2 object put ascii-bundle.js dist/assets/index-*.js
